main-strict:
	gcc -Wall -ansi -pedantic main.c -o main && ./main
main-strip:
	gcc -Wall -ansi -pedantic main.c -o main -s
main-simple:
	gcc main.c -o main && ./main
main-tcc:
	tcc main.c -o main && ./main